name: Package haxe-language-server

on:
  workflow_dispatch:
    inputs:
      vshaxe_version:
        type: string
        required: true
jobs:
  package_all:
    name: Package haxe-language-server
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      VERSION: ${{ inputs.vshaxe_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Update Packages
        run: sudo apt-get update -y
      - name: Install Dependencies
        run: sudo apt-get install -y npm nodejs git
      - name: Get haxe-language-server
        run: |
          git clone --depth 1 --branch ${VERSION} --recurse-submodules=server https://github.com/vshaxe/vshaxe.git
      - name: Build haxe-language-server
        run: |
          cd vshaxe/server
          npm ci
          npx lix run vshaxe-build -t language-server
          cd ../..
      - name: Repack haxe-language-server
        run: |
          mkdir build
          mv vshaxe/server/bin/server.js build/server.js
          rm -fr vshaxe
          mv build haxe-language-server
          tar -zcvf haxe-language-server-${VERSION}.tar.gz haxe-language-server
      - name: Create Release
        env: { GITHUB_TOKEN: "${{ github.token }}" }
        run: |
          gh release delete -y "haxe-language-server-$VERSION" || true
          gh release create -t "haxe-language-server-$VERSION" "haxe-language-server-$VERSION" haxe-language-server-*.tar.gz
