name: SwiftyRipgrep

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: SwiftyRipgrep-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_$(cat .xcode-version).app
      - name: Test
        run: swift test --package-path ./fixture
