name: testdata-inline-script-13
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Inline script
        run: |
          echo "Inline => ${{ env.HELLO }}"
          docker run busybox echo ${{ github.event_name }}
