name: habit-close
on:
  issues:
    types: [closed]
jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      ISSUE_TITLE: ${{ github.event.issue.title }}
    steps:
      - run: |
          curl -d "message=${{ env.ISSUE_TITLE }}"           -H "X-TYPETALK-TOKEN: ${{ secrets.TYPETALK_TOKEN }}"           https://typetalk.com/api/v1/topics/${{ secrets.TYPETALK_TOPIC_ID }}
