name: "ActionUsingUploadArtifactAction"
on: [push]
jobs:
  SomeJob:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/file.txt
