name: Example-UploadArtifact
on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Fake Step
        run: echo "No secrets or github context here"

      - name: Upload artifact
        uses: actions/upload-artifact@0123456789012345678901234567890123456789
        with:
          name: my-artifact
          path: .
