name: ExpressionInjectionCheck
on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: ${{ steps.example.outputs.image }}
    steps:
      - name: example
        id: example
        run: |
          echo "::set-output name=image::myorg/myimage:latest"
