on: push

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${stuff} ${otherstuff}"
        env:
          stuff: ${{ fromJSON(secrets.password) }}
          otherstuff: ${{ fromJson(secrets.otherstuff).field }}